AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'db/**'
    - 'bin/**'
    - 'config/**/*'

# Don't complain about top-level class documentation comments.
Documentation:
  Enabled: false

# Don't complain about long block lengths.
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '(\A|\s)#' # Don't get upset at comments longer than the line length.
    - 'authorize %' # Exclude Pundit authorization calls
    - 'belongs_to :'
    - 'has_many :'
    - 'has_and_belongs_to_many :'

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 150

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Don't require the magic comment for Ruby 2.3
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
